# https://golangci-lint.run/usage/quick-start/
run:
  timeout: 1m
  skip-dirs:
  skip-files:
   - protocol/mikrotik.go
   - protocol/mikrotik_test.go
  build-tags:
linters:
# https://golangci-lint.run/usage/linters/

  enable:

    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    #- bodyclose
    - containedctx
    - contextcheck
    #- cyclop
    - decorder
    #- depguard
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    #- exhaustive
    - exportloopref
    - gci
    - gochecknoinits
    #- gocognit
    #- goconst
    #- gocritic
    - gocyclo
    - godot
    #- godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    #- gomoddirectives
    - gomodguard
    - grouper
    - importas
    - interfacebloat
    #- lll
    #- makezero
    - misspell
    - nakedret
    #- nestif
    - nilerr
    - nlreturn
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    #- rowserrcheck // buggy on 1.54
    - stylecheck
    - tagliatelle
    - tenv
    - unconvert
    - unparam
    #- usestdlibvars
    #- varnamelen
    - wastedassign
    - whitespace
    - wrapcheck


linters-settings:
    lll:
      line-length: 140
issues:

